pub mod fizzbuzz;
pub mod k_closest;
pub mod merge_intervals;
pub mod palindrome_number;
pub mod smaller_numbers;
pub mod sort_colors;
pub mod sorting_the_sentence;
pub mod target_indices;
pub mod two_sum;
